# -*- encoding: utf-8 -*-

CHANNEL_VALIDITY = 'validity'
CHANNEL_VALIDITY_SCRAPY = 'validity_scrapy'
CHANNEL_QUERIES_ADD = 'queries_add'
CHANNEL_QUERY_DELETE = 'query_delete'
CHANNEL_QUERY_UPDATE = 'query_update'
CHANNEL_QUERY_GROUPING = 'query_grouping'
CHANNEL_SCAN_STATUS = 'scan_status'
CHANNEL_SCAN_QUERIES_UPDATE = 'scan_queries_update'
CHANNEL_POS_UPDATE_YANDEX = 'pos_update_yandex'
CHANNEL_POS_UPDATE_GOOGLE = 'pos_update_google'
CHANNEL_FREQUENCY_UPDATE = 'frequency_update'
CHANNEL_COPYWRITERS_UPDATE = 'cw_update'
CHANNEL_NOTIFICATIONS = 'notifications'
CHANNEL_GENERATE_COPYTASK = 'generate_copytask'
CHANNEL_REC_PAGINATE = 'rec_paginate'